<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  	<AssemblyName>Richasy.AgentKernel.Connectors.Ali</AssemblyName>
  	<RootNamespace>$(AssemblyName)</RootNamespace>
  	<TargetFramework>net9.0</TargetFramework>
  	<NoWarn>$(NoWarn)</NoWarn>
  	<IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <Import Project="$(RepoRoot)/src/nuget-package.props" />
  
  <PropertyGroup>
  	<!-- NuGet Package Settings -->
  	<Title>Agent Kernel - Ali connectors</Title>
  	<Description>Agent Kernel connectors for Alibaba Clound, include Chat and Translate services</Description>
  </PropertyGroup>
  
  <ItemGroup>
  	<PackageReference Include="RichasyKernel.Abstractions" />
  	<PackageReference Include="RichasyKernel.Core" />
  </ItemGroup>
  
  <ItemGroup>
  	<ProjectReference Include="..\..\AgentKernel.Core\AgentKernel.Core.csproj" />
	<ProjectReference Include="..\..\Libs\Microsoft.Extensions.AI.OpenAI\Microsoft.Extensions.AI.OpenAI.csproj">
	  <PrivateAssets>all</PrivateAssets>
	</ProjectReference>
  </ItemGroup>
  
</Project>
