namespace AgentKernel.Core.OpenAI.Assistants;

[CodeGenModel("UnknownRunStepDetailsToolCallsCodeObjectCodeInterpreterOutputsObject")]
internal partial class UnknownRunStepDetailsToolCallsCodeObjectCodeInterpreterOutputsObject
{
}