namespace Richasy.AgentKernel.Core.OpenAI.Assistants;

[CodeGenModel("UnknownRunStepDeltaStepDetailsToolCallsObjectToolCallsObject")]
internal partial class UnknownRunStepDeltaStepDetailsToolCallsObjectToolCallsObject
{
}