<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
  	<AssemblyName>Richasy.AgentKernel.Connectors.Ollama</AssemblyName>
  	<RootNamespace>$(AssemblyName)</RootNamespace>
  	<TargetFramework>net9.0</TargetFramework>
  	<NoWarn>$(NoWarn)</NoWarn>
  	<IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <Import Project="$(RepoRoot)/src/nuget-package.props" />
  
  <PropertyGroup>
  	<!-- NuGet Package Settings -->
  	<Title>Agent Kernel - Ollama connectors</Title>
  	<Description>Agent Kernel connectors for Ollama.</Description>
  </PropertyGroup>
  
  <ItemGroup>
  	<PackageReference Include="Microsoft.Extensions.AI.Ollama" />
	<PackageReference Include="RichasyKernel.Abstractions" />
  </ItemGroup>
  
  <ItemGroup>
  	<ProjectReference Include="..\..\AgentKernel.Core\AgentKernel.Core.csproj" />
  </ItemGroup>
  
</Project>
