<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
  	<AssemblyName>Richasy.AgentKernel.Definitions</AssemblyName>
  	<RootNamespace>Richasy.AgentKernel</RootNamespace>
  	<TargetFramework>net9.0</TargetFramework>
  	<IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  
  <Import Project="$(RepoRoot)/src/nuget-package.props" />
  
  <PropertyGroup>
  	<!-- NuGet Package Settings -->
  	<Title>Agent Kernel - Definitions</Title>
  	<Description>The core of the AI library, which contains constants definitions and config definitions.</Description>
  </PropertyGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\AgentKernel.Core\AgentKernel.Core.csproj" />
  </ItemGroup>
  
</Project>
