<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  	<TargetFramework>net9.0</TargetFramework>
  	<AssemblyName>Richasy.AgentKernel.Core.AzureInference</AssemblyName>
  	<RootNamespace>$(AssemblyName)</RootNamespace>
  	<DisableEnhancedAnalysis>true</DisableEnhancedAnalysis>
  	<GenerateAPIListing>true</GenerateAPIListing>
  	<NoWarn>$(NoWarn);CS1591;AZC0012;AZC0102;CS8002;CS0436;AZC0112</NoWarn>
  	<ImplicitUsings>enable</ImplicitUsings>
  	<LangVersion>preview</LangVersion>
  	<Nullable>disable</Nullable>
  </PropertyGroup>
  
  <Import Project="$(RepoRoot)/src/nuget-package.props" />
  
  <PropertyGroup>
  	<!-- NuGet Package Settings -->
  	<Title>Agent Kernel - Core - AzureInference</Title>
  	<Description>Version after AOT based on azure-sdk</Description>
  </PropertyGroup>
  
  <ItemGroup>
  	<PackageReference Include="Azure.Core" />
  </ItemGroup>

  <PropertyGroup Label="Trimmable" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">
  	<IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>
  	<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
  	<IsTrimmable>true</IsTrimmable>
  	<SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
  	<TrimmerSingleWarn>false</TrimmerSingleWarn>
  </PropertyGroup>
  
</Project>
