<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
  	<AssemblyName>Richasy.AgentKernel.Connectors.Volcano</AssemblyName>
  	<RootNamespace>$(AssemblyName)</RootNamespace>
  	<TargetFramework>net9.0</TargetFramework>
  	<NoWarn>$(NoWarn)</NoWarn>
  	<IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <Import Project="$(RepoRoot)/src/nuget-package.props" />
  
  <PropertyGroup>
  	<!-- NuGet Package Settings -->
  	<Title>Agent Kernel - Volcano connectors</Title>
  	<Description>Agent Kernel connectors for Volcano, include DouBao and translate services.</Description>
  </PropertyGroup>
  
  <ItemGroup>
	<PackageReference Include="RichasyKernel.Abstractions" />
	<PackageReference Include="RichasyKernel.Core" />
  </ItemGroup>
  
  <ItemGroup>
  	<ProjectReference Include="..\..\AgentKernel.Core\AgentKernel.Core.csproj" />
	<ProjectReference Include="..\..\Libs\AgentKernel.Extensions.AI.OpenAI\AgentKernel.Extensions.AI.OpenAI.csproj" />
  </ItemGroup>
  
</Project>
