// Copyright (c) Richasy. All rights reserved.
// Licensed under the MIT License.

using Richasy.AgentKernel.Models;
using System.Globalization;

namespace Richasy.AgentKernel.Connectors.Azure.Core;

public sealed partial class AzureTranslateClient
{
    /// <inheritdoc/>
    public TranslationLanguages GetSupportedLanguages()
    {
        var languages = new Dictionary<string, CultureInfo?>
        {
            { "auto", null },
            { "af", new("af") },
            { "am", new("am") },
            { "ar", new("ar") },
            { "as", new("as") },
            { "az", new("az") },
            { "ba", new("ba") },
            { "bg", new("bg") },
            { "bho", new("bho") },
            { "bn", new("bn") },
            { "bo", new("bo") },
            { "brx", new("brx") },
            { "bs", new("bs") },
            { "ca", new("ca") },
            { "cs", new("cs") },
            { "cy", new("cy") },
            { "da", new("da") },
            { "de", new("de") },
            { "doi", new("doi") },
            { "dsb", new("dsb") },
            { "dv", new("dv") },
            { "el", new("el") },
            { "en", new("en") },
            { "es", new("es") },
            { "et", new("et") },
            { "eu", new("eu") },
            { "fa", new("fa") },
            { "fi", new("fi") },
            { "fil", new("fil") },
            { "fj", new("fj") },
            { "fo", new("fo") },
            { "fr", new("fr") },
            { "fr-CA", new("fr-CA") },
            { "ga", new("ga") },
            { "gl", new("gl") },
            { "gom", new("gom") },
            { "gu", new("gu") },
            { "ha", new("ha") },
            { "he", new("he") },
            { "hi", new("hi") },
            { "hr", new("hr") },
            { "hsb", new("hsb") },
            { "ht", new("ht") },
            { "hu", new("hu") },
            { "hy", new("hy") },
            { "id", new("id") },
            { "ig", new("ig") },
            { "is", new("is") },
            { "iu", new("iu") },
            { "iu-Latn", new("iu-Latn") },
            { "ja", new("ja") },
            { "ka", new("ka") },
            { "kk", new("kk") },
            { "km", new("km") },
            { "kn", new("kn") },
            { "ko", new("ko") },
            { "ks", new("ks") },
            { "ku", new("ku") },
            { "ky", new("ky") },
            { "ln", new("ln") },
            { "lo", new("lo") },
            { "lt", new("lt") },
            { "lug", new("lug") },
            { "lv", new("lv") },
            { "lzh", new("lzh") },
            { "mai", new("mai") },
            { "mg", new("mg") },
            { "mi", new("mi") },
            { "mk", new("mk") },
            { "ml", new("ml") },
            { "mn-Cyrl", new("mn-Cyrl") },
            { "mn-Mong", new("mn-Mong") },
            { "mni", new("mni") },
            { "mr", new("mr") },
            { "ms", new("ms") },
            { "mt", new("mt") },
            { "my", new("my") },
            { "nb", new("nb") },
            { "ne", new("ne") },
            { "nl", new("nl") },
            { "nso", new("nso") },
            { "nya", new("nya") },
            { "or", new("or") },
            { "pa", new("pa") },
            { "pl", new("pl") },
            { "ps", new("ps") },
            { "pt", new("pt") },
            { "pt-PT", new("pt-PT") },
            { "ro", new("ro") },
            { "ru", new("ru") },
            { "run", new("run") },
            { "rw", new("rw") },
            { "sd", new("sd") },
            { "si", new("si") },
            { "sk", new("sk") },
            { "sl", new("sl") },
            { "sm", new("sm") },
            { "sn", new("sn") },
            { "so", new("so") },
            { "sq", new("sq") },
            { "sr-Cyrl", new("sr-Cyrl") },
            { "sr-Latn", new("sr-Latn") },
            { "st", new("st") },
            { "sv", new("sv") },
            { "sw", new("sw") },
            { "ta", new("ta") },
            { "te", new("te") },
            { "th", new("th") },
            { "ti", new("ti") },
            { "tk", new("tk") },
            { "tlh-Latn", new("tlh-Latn") },
            { "tlh-Piqd", new("tlh-Piqd") },
            { "tn", new("tn") },
            { "to", new("to") },
            { "tr", new("tr") },
            { "tt", new("tt") },
            { "ty", new("ty") },
            { "ug", new("ug") },
            { "uk", new("uk") },
            { "ur", new("ur") },
            { "uz", new("uz") },
            { "vi", new("vi") },
            { "xh", new("xh") },
            { "yo", new("yo") },
            { "yue", new("yue") },
            { "zh-Hans", new("zh-Hans") },
            { "zh-Hant", new("zh-Hant") },
            { "zu", new("zu") },
        };

        return new TranslationLanguages(languages, languages.Skip(1).ToDictionary());
    }
}
