<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net9.0</TargetFramework>
	<AssemblyName>Richasy.AgentKernel.Core.AzureOpenAI</AssemblyName>
	<RootNamespace>$(AssemblyName)</RootNamespace>
    <DisableEnhancedAnalysis>true</DisableEnhancedAnalysis>
    <GenerateAPIListing>true</GenerateAPIListing>
    <NoWarn>$(NoWarn);CS1591;AZC0012;AZC0102;CS8002;CS0436;AZC0112;OPENAI001;OPENAI002</NoWarn>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
    <Nullable>disable</Nullable>
	<IsTrimmable Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">true</IsTrimmable>
	<IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>
  </PropertyGroup>
  
  <Import Project="$(RepoRoot)/src/nuget-package.props" />

  <PropertyGroup>
  	<!-- NuGet Package Settings -->
  	<Title>Agent Kernel - Core - AzureOpenAI</Title>
  	<Description>Version after AOT based on azure-sdk</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Core" />
    <PackageReference Include="System.Memory.Data" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgentKernel.Core.OpenAI\AgentKernel.Core.OpenAI.csproj" />
  </ItemGroup>
</Project>
