<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<AssemblyName>Richasy.AgentKernel.Connectors.AzureOpenAI</AssemblyName>
	<RootNamespace>$(AssemblyName)</RootNamespace>
    <TargetFramework>net9.0</TargetFramework>
	<NoWarn>$(NoWarn)</NoWarn>
	<IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AgentKernel.Core\AgentKernel.Core.csproj" />
    <ProjectReference Include="..\..\Libs\richasy-kernel\src\RichasyKernel.Abstractions\RichasyKernel.Abstractions.csproj" />
  </ItemGroup>

</Project>
