<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
  	<AssemblyName>Richasy.AgentKernel.Connectors.Baidu</AssemblyName>
  	<RootNamespace>$(AssemblyName)</RootNamespace>
  	<TargetFramework>net9.0</TargetFramework>
  	<NoWarn>$(NoWarn)</NoWarn>
  	<IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <Import Project="$(RepoRoot)/src/nuget-package.props" />
  
  <PropertyGroup>
  	<!-- NuGet Package Settings -->
  	<Title>Agent Kernel - Baidu connectors</Title>
  	<Description>Agent Kernel connectors for Baidu, include Ernie and Translate services</Description>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="System.Memory.Data" />
	<PackageReference Include="RichasyKernel.Abstractions" />
	<PackageReference Include="RichasyKernel.Core" />
  </ItemGroup>
  
  <ItemGroup>
  	<ProjectReference Include="..\..\AgentKernel.Core\AgentKernel.Core.csproj" />
  </ItemGroup>
  
</Project>
