<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
  	<AssemblyName>Richasy.AgentKernel.Connectors.SiliconFlow</AssemblyName>
  	<RootNamespace>$(AssemblyName)</RootNamespace>
  	<TargetFramework>net9.0</TargetFramework>
  	<NoWarn>$(NoWarn)</NoWarn>
  	<IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  
  <ItemGroup>
	<PackageReference Include="RichasyKernel.Abstractions" />
  </ItemGroup>
  
  <ItemGroup>
  	<ProjectReference Include="..\..\AgentKernel.Core\AgentKernel.Core.csproj" />
	<ProjectReference Include="..\..\Libs\Microsoft.Extensions.AI.OpenAI\Microsoft.Extensions.AI.OpenAI.csproj" />
  </ItemGroup>
  
</Project>
